### ISSUE TITLE
Association Type cannot be filled via the frontend

### ISSUE THREAD

**Issue by nadinetamm** [DINA-Web/collection-specs#176]
When I try to create a material sample association in a material sample, the Association Type field cannot be filled.
Clicking on one of the selection options has no effect at all - the field simply remains empty. 
If I send the material sample association information via the backend, it works, but the information is not visible!

![DINA-MaterialSampleAsso](https://github.com/DINA-Web/collection-specs/assets/115980888/e9825af8-446e-43db-8b3f-59ee794a26e5)

**Comment by brandonandre** [comment]
Hi @nadinetamm, 

Thank you for reporting this issue, I will keep you updated once it gets fixed so association types can be edited/viewed on the front end again.

Thanks!

Brandon

**Comment by nadinetamm** [comment]
Hi Brandon, 
can you give us an update on when this bug can be fixed?
Thanks!
Nadine

**Comment by brandonandre** [comment]
Hey Nadine,

Sorry for the delay in response, we actually just released the new Collection API today with the fix for this issue:

![image](https://github.com/DINA-Web/collection-specs/assets/3820842/03a0cd86-27b2-4a88-9ded-93a458b2f2ec)

Tested saving and editing the association and it now lets you select an option from the dropdown. I'll mark this issue as closed but please let me know if you find any issues when trying it out.

Thank you!

Brandon
